:Author: jessekhach
:Email: jessekhach@gmail.com
:Date: 05/01/2021
:Revision: 0.0
:License: Public Domain

= Project: Arduino Obstacle Awareness System

This system uses an Arduino Mega with ultrasonic sensors in order to detect obstacles within a certain distance.

== Step 1: Installation

1. Download all files

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact jessekhach https://id.arduino.cc/jessekhach

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name                     | Quantity

| A1 | Arduino Mega 2560 Rev3        | 1
| R1 | 330Ω Resistor                 | 1
| S1 | Waterproof Ultrasonic Sensor  | 5
| L1 | Waterproof LED Strip          | 1
| V1 | Vibration Motor               | 3

|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
